const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:localStorage.kcToken||'',user:null,keepers:[],matches:[],match:null,events:[]};
const api=async(path,opt={})=>{opt.headers=opt.headers||{}; if(state.token)opt.headers.Authorization='Bearer '+state.token;if(opt.body&&!(opt.body instanceof FormData)){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}const r=await fetch(path,opt);if(!r.ok){let m='Request failed';try{m=(await r.json()).detail||m}catch{}throw Error(m)}return r.headers.get('content-type')?.includes('json')?r.json():r};
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function fmt(sec){sec=Number(sec||0);return `${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`}
function show(id){$$('.view').forEach(v=>v.classList.add('hidden'));$('#view-'+id).classList.remove('hidden');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));if(id==='dashboard')renderDashboard();if(id==='keepers')renderKeepers();if(id==='newmatch')prepMatchForm();if(id==='progress')renderProgress()}
async function boot(){if(!state.token)return;try{state.user=await api('/api/me');state.keepers=await api('/api/keepers');state.matches=await api('/api/matches');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#userLabel').textContent=`${state.user.name} · ${state.user.role}`;$('#welcome').textContent=`Welcome, ${state.user.name.split(' ')[0]}`;show('dashboard')}catch(e){localStorage.removeItem('kcToken');state.token=''}}
$$('[data-auth]').forEach(b=>b.onclick=()=>{let login=b.dataset.auth==='login';$$('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',!login);$('#registerForm').classList.toggle('hidden',login)});
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{let x=await api('/api/login',{method:'POST',body:{email:$('#loginEmail').value,password:$('#loginPassword').value}});state.token=x.token;localStorage.kcToken=x.token;await boot()}catch(x){toast(x.message)}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{let x=await api('/api/register',{method:'POST',body:{name:$('#regName').value,email:$('#regEmail').value,password:$('#regPassword').value,role:$('#regRole').value}});state.token=x.token;localStorage.kcToken=x.token;await boot()}catch(x){toast(x.message)}};
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}catch{}localStorage.removeItem('kcToken');location.reload()};
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
async function refresh(){state.keepers=await api('/api/keepers');state.matches=await api('/api/matches')}
async function keeperScore(kid){let p=await api('/api/progress/'+kid);let vals=p.filter(x=>x.overall>0);return vals.length?vals.at(-1).overall:0}
async function renderDashboard(){await refresh();let kc=$('#keeperCards');kc.innerHTML='';for(let k of state.keepers){let score=await keeperScore(k.id);kc.insertAdjacentHTML('beforeend',`<div class="card keeperCard" data-k="${k.id}"><div class="eyebrow">${k.team||'KEEPER'}</div><h3>${k.name}</h3><div class="meta">${[k.club,k.height_cm?`${k.height_cm} cm`:null].filter(Boolean).join(' · ')||'Profile ready'}</div><div class="score">${score||'—'}</div><div class="meta">Current rating</div></div>`)}if(!state.keepers.length)kc.innerHTML='<div class="panel">Create your first keeper profile to begin.</div>';let rm=$('#recentMatches');rm.innerHTML=state.matches.map(m=>`<div class="matchrow"><div><strong>${m.keeper_name} vs ${m.opponent}</strong><span>${m.match_date} · ${m.competition||'Match'} · ${m.result||'Result not entered'}</span></div><div class="matchActions"><button class="ghost openMatch" data-id="${m.id}">Open</button><button class="danger deleteMatch" data-id="${m.id}" data-label="${m.keeper_name} vs ${m.opponent}">Delete</button></div><button class="ghost secondaryAction openReport" data-id="${m.id}">Report</button></div>`).join('')||'<div class="panel meta">No matches yet.</div>';$$('.openMatch').forEach(b=>b.onclick=()=>openMatch(b.dataset.id));$$('.openReport').forEach(b=>b.onclick=()=>openReport(b.dataset.id));$$('.deleteMatch').forEach(b=>b.onclick=()=>deleteMatch(b.dataset.id,b.dataset.label))}
async function deleteMatch(id,label){if(!confirm(`Delete ${label}? This will permanently remove its tagged actions and uploaded video.`))return;try{await api('/api/matches/'+id,{method:'DELETE'});if(state.match?.id===id)state.match=null;await refresh();toast('Match deleted');show('dashboard')}catch(x){toast(x.message)}}
function renderKeepers(){let el=$('#keepersList');el.innerHTML=state.keepers.map(k=>`<div class="card"><div class="eyebrow">${k.team||'GOALKEEPER'}</div><h3>${k.name}</h3><div class="meta">${[k.club,k.dob,k.height_cm?`${k.height_cm} cm`:null,k.dominant_foot?`${k.dominant_foot} foot`:null].filter(Boolean).join(' · ')}</div></div>`).join('')||'<div class="panel">No keepers yet.</div>'}
$('#addKeeperBtn').onclick=()=>$('#keeperForm').classList.remove('hidden');$('#cancelKeeper').onclick=()=>$('#keeperForm').classList.add('hidden');
$('#keeperForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/keepers',{method:'POST',body:{name:$('#kName').value,dob:$('#kDob').value||null,club:$('#kClub').value||null,team:$('#kTeam').value||null,height_cm:Number($('#kHeight').value)||null,dominant_foot:$('#kFoot').value||null}});e.target.reset();$('#keeperForm').classList.add('hidden');await refresh();renderKeepers();toast('Keeper created')}catch(x){toast(x.message)}};
function prepMatchForm(){let s=$('#mKeeper');s.innerHTML=state.keepers.map(k=>`<option value="${k.id}">${k.name}</option>`).join('');$('#mDate').value ||= new Date().toISOString().slice(0,10)}
$('#matchForm').onsubmit=async e=>{e.preventDefault();if(!state.keepers.length)return toast('Create a keeper first');try{let x=await api('/api/matches',{method:'POST',body:{keeper_id:$('#mKeeper').value,opponent:$('#mOpponent').value,match_date:$('#mDate').value,result:$('#mResult').value||null,competition:$('#mCompetition').value||null,minutes:Number($('#mMinutes').value)||90}});await refresh();openMatch(x.id)}catch(x){toast(x.message)}};
async function openMatch(id){state.match=state.matches.find(x=>x.id===id)|| (await api('/api/matches')).find(x=>x.id===id);state.events=await api(`/api/matches/${id}/events`);let m=state.match;$('#matchTitle').innerHTML=`<div class="matchHeading"><div><div class="eyebrow">MATCH ANALYSIS</div><h2>${m.keeper_name} vs ${m.opponent}</h2><p class="meta">${m.match_date} · ${m.competition||'Match'} · ${m.result||'Result not entered'}</p></div><button class="danger" id="deleteCurrentMatch">Delete match</button></div>`;$('#deleteCurrentMatch').onclick=()=>deleteMatch(m.id,`${m.keeper_name} vs ${m.opponent}`);let vc=$('.videoCard'),v=$('#video');if(m.video_name){vc.classList.add('hasvideo');v.src=`/api/matches/${id}/video?token=${encodeURIComponent(state.token)}`; // fetch auth not possible on video, replace with blob below
 try{let r=await fetch(`/api/matches/${id}/video`,{headers:{Authorization:'Bearer '+state.token}});if(r.ok)v.src=URL.createObjectURL(await r.blob())}catch{}
}else{vc.classList.remove('hasvideo');v.removeAttribute('src')}renderEvents();showRaw('match')}
function showRaw(id){$$('.view').forEach(v=>v.classList.add('hidden'));$('#view-'+id).classList.remove('hidden');$$('nav button').forEach(b=>b.classList.remove('active'))}
$('#uploadVideo').onclick=async()=>{let f=$('#videoFile').files[0];if(!f)return toast('Choose a video first');let fd=new FormData();fd.append('file',f);try{$('#uploadVideo').textContent='Uploading…';await api(`/api/matches/${state.match.id}/video`,{method:'POST',body:fd});toast('Footage uploaded');await refresh();await openMatch(state.match.id)}catch(x){toast(x.message)}finally{$('#uploadVideo').textContent='Upload footage'}};
$('#useTime').onclick=()=>$('#eSecond').value=$('#video').currentTime.toFixed(1);
$('#eventForm').onsubmit=async e=>{e.preventDefault();try{await api(`/api/matches/${state.match.id}/events`,{method:'POST',body:{second:Number($('#eSecond').value)||0,event_type:$('#eType').value,outcome:$('#eOutcome').value||null,technique:Number($('#eTechnique').value),decision_making:Number($('#eDecision').value),positioning:Number($('#ePositioning').value),execution:Number($('#eExecution').value),note:$('#eNote').value||null}});state.events=await api(`/api/matches/${state.match.id}/events`);renderEvents();$('#eNote').value='';toast('Action tagged')}catch(x){toast(x.message)}};
function renderEvents(){$('#eventCount').textContent=`${state.events.length} actions`;$('#events').innerHTML=state.events.map(e=>`<div class="event"><button class="eventTime seek" data-s="${e.second}">${fmt(e.second)}</button><div><strong>${e.event_type}</strong><small>${e.outcome||''}${e.note?' · '+e.note:''}</small></div><button class="del" data-id="${e.id}">×</button></div>`).join('')||'<p class="meta">No actions tagged yet.</p>';$$('.seek').forEach(b=>b.onclick=()=>{$('#video').currentTime=Number(b.dataset.s);$('#video').play().catch(()=>{})});$$('.del').forEach(b=>b.onclick=async()=>{await api('/api/events/'+b.dataset.id,{method:'DELETE'});state.events=await api(`/api/matches/${state.match.id}/events`);renderEvents()})}
async function openReport(id){let x=await api(`/api/matches/${id}/report`),r=x.report,m=x.match;let bars=Object.entries(r.categories).map(([k,v])=>`<div class="barrow"><span>${k}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><strong>${v}</strong></div>`).join('');$('#reportContent').innerHTML=`<div class="eyebrow">MATCH REPORT</div><div class="ratingHero"><div class="big">${r.overall||'—'}</div><div><h2>${m.opponent}</h2><div class="meta">${m.match_date} · ${x.event_count} tagged actions</div></div></div><div class="bars">${bars||'<div class="panel meta">Tag actions to generate ratings.</div>'}</div><div class="reportgrid"><div class="panel"><div class="eyebrow">MATCH STRENGTH</div><h3>${r.strength}</h3><p>${r.summary}</p></div><div class="panel"><div class="eyebrow">DEVELOPMENT FOCUS</div><h3>${r.focus}</h3><ol class="training">${r.training.map(t=>`<li>${t}</li>`).join('')}</ol></div></div>`;showRaw('report')}
async function renderProgress(){await refresh();let s=$('#progressKeeper');s.innerHTML=state.keepers.map(k=>`<option value="${k.id}">${k.name}</option>`).join('');s.onchange=drawProgress;if(state.keepers.length)drawProgress();else $('#progressContent').innerHTML='<p class="meta">Create a keeper first.</p>'}
async function drawProgress(){let p=await api('/api/progress/'+$('#progressKeeper').value);let valid=p.filter(x=>x.overall>0);let trend=valid.length>1?valid.at(-1).overall-valid[0].overall:0;$('#progressContent').innerHTML=`<div class="sectionhead"><h3>Match ratings</h3><span class="pill">${trend>0?'+':''}${trend} overall</span></div>${p.map(x=>`<div class="progressRow"><span>${x.date}</span><div><strong>${x.opponent}</strong><div class="meta">${Object.entries(x.categories).map(([k,v])=>`${k} ${v}`).join(' · ')||'No tagged actions'}</div></div><div class="score" style="font-size:28px">${x.overall||'—'}</div></div>`).join('')||'<p class="meta">No matches yet.</p>'}`}
boot();

